name: Build wgpu-native

on:
  workflow_dispatch:

env:
  WGPU_REF: v0.19.1.1
  ANDROID_MIN_SDK: "21"
  
jobs:
  build-wgpu:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      CARGO_BUILD_TARGET: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: build - android/arm64
            os: ubuntu-22.04
            target: aarch64-linux-android
            goos: android
            goarch: arm64
            setup_env: |
              set -x
              export CC=$ANDROID_NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android$ANDROID_MIN_SDK-clang

              echo "CC=$CC" >> $GITHUB_ENV
              echo "CXX=$CC++" >> $GITHUB_ENV
              echo "CLANG_PATH=$CC" >> $GITHUB_ENV
              echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$CC" >> $GITHUB_ENV

          - name: build - android/arm
            os: ubuntu-22.04
            target: armv7-linux-androideabi
            goos: android
            goarch: arm
            setup_env: |
              set -x
              export CC=$ANDROID_NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi$ANDROID_MIN_SDK-clang

              echo "CC=$CC" >> $GITHUB_ENV
              echo "CXX=$CC++" >> $GITHUB_ENV
              echo "CLANG_PATH=$CC" >> $GITHUB_ENV
              echo "CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER=$CC" >> $GITHUB_ENV
    steps:
      # Checkout
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - if: ${{ matrix.goos == 'android' }}
        name: Setup Android NDK
        shell: bash
        run: |
          set -ex
          mkdir -p /tmp/go-webgpu-ndk/
          cd /tmp/go-webgpu-ndk/

          # ndkVersion "25.2.9519653"
          curl -LO https://dl.google.com/android/repository/android-ndk-r25c-linux.zip

          unzip android-ndk-r25c-linux.zip
          rm android-ndk-r25c-linux.zip
          export ANDROID_NDK_PATH=$PWD/android-ndk-r25c

          echo "ANDROID_NDK_PATH=$ANDROID_NDK_PATH" >> $GITHUB_ENV
          echo "LIBCLANG_PATH=$ANDROID_NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/lib64/libclang.so.13" >> $GITHUB_ENV
          echo "LLVM_CONFIG_PATH=$ANDROID_NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-config" >> $GITHUB_ENV
          echo "BINDGEN_EXTRA_CLANG_ARGS='-isysroot $ANDROID_NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/sysroot'" >> $GITHUB_ENV

      - name: Setup Environment
        shell: bash
        run: ${{ matrix.setup_env }}

      - name: Build
        shell: bash
        run: |
          set -ex

          git clone --recursive https://github.com/gfx-rs/wgpu-native.git tmp
          cd tmp
          git checkout $WGPU_COMMIT

          # workaround missing libgcc in ndk r23+
          if [ ${{ matrix.goos }} == "android" ]; then
            mkdir -p tmp-lib
            echo "INPUT(-lunwind)" | tee tmp-lib/libgcc.a
            export RUSTFLAGS="-L $PWD/tmp-lib"
          fi

          cargo build --release
          ls -al target/${{ matrix.target }}/release/

          if [ ${{ matrix.goos }} == "ios" ]; then
            mv target/${{ matrix.target }}/release/libwgpu_native.dylib target/${{ matrix.target }}/release/${{ matrix.goos }}_${{ matrix.goarch }}_libwgpu_native.dylib
          else
            mv target/${{ matrix.target }}/release/libwgpu_native.so target/${{ matrix.target }}/release/${{ matrix.goos }}_${{ matrix.goarch }}_libwgpu_native.so
          fi

      - uses: actions/upload-artifact@v3
        with:
          name: wgpu-artifacts
          path: |
            ${{ github.workspace }}/tmp/target/${{ matrix.target }}/release/${{ matrix.goos }}_${{ matrix.goarch }}_libwgpu_native.so
